config/routes.rb
KillOrCure::Application.routes.draw do
  get "/about"       => "home#index",    :as => :homepage
  get "/stats"       => "stats#index",   :as => :stats
  get "/"            => "results#index"
  get "/a-z/:letter" => "results#index", :as => :results
  get "/done"        => "votes#done",    :as => :done
  resources :votes
  resources :corrections
end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :votes
  has_many :taggings
  has_many :terms, :through => :taggings
  has_many :normalized_terms, :through => :normalized_taggings

  scope :to_do, -> { order("articles.votes_count ASC, RANDOM()") }
  scope :most_voted, -> { order("articles.votes_count DESC") }

  def causes
    votes.select{ |v| v.effect == "cause" }.map{ |v| v.things }.flatten.sort.uniq
  end

  def preventors
    votes.select{ |v| v.effect == "prevent" }.map{ |v| v.things }.flatten.sort.uniq
  end
end

app/models/normalized_tagging.rb
class NormalizedTagging < ActiveRecord::Base
  belongs_to :article
  belongs_to :normalized_term
  scope :uncontroversial, -> { where("votes_against < 3") }
end

app/models/normalized_term.rb
class NormalizedTerm < ActiveRecord::Base
  has_many :terms
  has_many :normalized_taggings
  has_many :articles,
           :through    => :normalized_taggings

  def uncontroversial_taggings
    normalized_taggings.uncontroversial
  end

  def self.[](value)
    n = find_by_value(value) || create!(:value => value)
  end

  def causes_articles
    uncontroversial_taggings.select{ |t| !t.good? }.map{ |t| t.article }
  end

  def prevents_articles
    uncontroversial_taggings.select{ |t| t.good? }.map{ |t| t.article }
  end

  def causes?
    uncontroversial_taggings.any?{ |t| !t.good? }
  end

  def prevents?
    uncontroversial_taggings.any?{ |t| t.good? }
  end

  def effect
    case [!!prevents?, !!causes?]
    when [false, true]
      :cause
    when [true, false]
      :prevent
    when [true, true]
      :both
    end
  end

  def plural?
    value =~ /s$/i
  end
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :article
  belongs_to :term
end

app/models/term.rb
class Term < ActiveRecord::Base
  belongs_to :normalized_term
  has_many :taggings
  has_many :articles, :through => :taggings

  def self.[](value)
    n = find_by_value(value) || create!(:value => value)
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :article, :counter_cache => true

  scope :causing,    -> { where(effect: 'cause') }
  scope :preventing, -> { where(effect: 'prevent') }

  def things
    (general || "").split(/,\s*/).map{ |t| t.downcase }
  end
end

app/controllers/application_controller.rb
# Filters added to this controller apply to all controllers in the application.
# Likewise, all the methods added will be available for all controllers.

class ApplicationController < ActionController::Base
  helper :all # include all helpers, all the time
  protect_from_forgery # See ActionController::RequestForgeryProtection for details

  before_action :load_percent_complete

  def load_percent_complete
    @percent_complete = [(Vote.count * 100) / (Article.count * 3), 100].min
  end

  # Scrub sensitive parameters from your log
  # filter_parameter_logging :password
end

app/controllers/corrections_controller.rb
class CorrectionsController < ApplicationController
  def new
    @backlink = request.env["HTTP_REFERER"] || "/"
    @tagging = NormalizedTagging.find_by_article_id_and_normalized_term_id_and_good(params[:article_id], params[:normalized_term_id], params[:good]=="1")
  end

  def create
    NormalizedTagging.increment_counter(:votes_against, params[:id])
    redirect_to params[:backlink]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  def index
    @letters = NormalizedTerm.connection.select_all("SELECT DISTINCT LOWER(SUBSTR(value, 1, 1)) AS letter FROM normalized_terms").map{ |r| r["letter"] }.sort
    if params[:page]
      @terms = NormalizedTerm.paginate(
                 :page    => params[:page],
                 :order   => "LOWER(normalized_terms.value) ASC",
                 :include => [:articles])
    else
      @letter = ((params[:letter] || '')[/^./] || 'a').downcase
      @terms =
        NormalizedTerm.where(
          [
            "normalized_terms.value LIKE ? OR normalized_terms.value LIKE ?",
            @letter + "%",
            @letter.upcase + "%"
          ]
        ).
        where(
          "EXISTS (SELECT 1 FROM normalized_taggings
            WHERE normalized_taggings.normalized_term_id = normalized_terms.id
            AND normalized_taggings.votes_against < 3)"
        ).
        order("LOWER(normalized_terms.value) ASC").
        includes(:articles).
        all
    end
  end
end

app/controllers/stats_controller.rb
class StatsController < ApplicationController
  def index
    @articles = Article.most_voted.paginate(:page => params[:page], :include => [:votes])
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def new
    @article = Article.to_do.first
    @vote = @article.votes.build
  end

  def create
    attributes = {:article_id => params[:vote][:article_id], :general => params[:vote][:general]}
    if params[:prevent]
      attributes[:effect] = "prevent"
    elsif params[:cause]
      attributes[:effect] = "cause"
    else
      attributes[:effect] = "skip"
    end
    if attributes[:effect] == "skip" || attributes[:general].present?
      Vote.create!(attributes)
    end
    redirect_to new_vote_path
  end
end

app/helpers/application_helper.rb
# Methods added to this helper will be available to all templates in the application.
module ApplicationHelper
end

app/views/corrections/new.html.erb
<p>If this entry is incorrect, i.e. it doesn't refer to the item mentioned, or the conclusion is invalid, please submit a report. The item will be removed from the results in due course.</p>
<% form_tag corrections_path(:id => @tagging.id) do %>
  <table>
    <tr>
      <th>Thing</th>
      <td><%= h(@tagging.normalized_term.value) %></td>
    </tr>
    <tr>
      <th>Effect</th>
      <td><%= @tagging.good? ? "Prevents cancer" : "Causes cancer" %></td>
    </tr>
    <tr>
      <th>Headline</th>
      <td><%= h(@tagging.article.title) %></td>
    </tr>
    <tr>
      <th>Summary</th>
      <td><%= h(@tagging.article.summary) %></td>
    </tr>
    <tr>
      <th>URL</th>
      <td><%= link_to(@tagging.article.link, @tagging.article.link, :target => "_blank") %></td>
    </tr>
  </table>

  <%= hidden_field_tag "backlink", @backlink %>

  <p>
    <input type="submit" value="Yes, this is incorrect" />
    <%= link_to "No, take me back", :back %>
  </p>
<% end %>

app/views/home/index.html.erb
<p>
  As <a href="http://www.badscience.net/2007/12/a-rather-long-build-up-to-one-punchline/">Ben Goldacre wrote</a>:
</p>
<blockquote>
  <p>
    The Daily Mail, as you know, is engaged in a philosophical project of
    mythic proportions: for many years now it has diligently been sifting
    through all the inanimate objects in the world, soberly dividing them into
    the ones which either cause – or cure – cancer.
  </p>
</blockquote>
<p>
  The Daily Mail frequently brings us news of which objects have been
  discovered to <strong>cause</strong> cancer, and which have been shown to
  <strong>prevent</strong> it. In some cases, they do both.
</p>
<p>
  In order to make sense of this vast resource of clinical information, I’ve
  scraped the Daily Mail’s website for articles mentioning cancer. To distil
  this wisdom down into an easily comprehensible form, though, I need some help.
</p>
<p>
  You can assist me by classifying articles, saying
</p>
<ul>
  <li>
    What the article refers to, e.g. <em>wine</em> or <em>Facebook</em>.
  </li>
  <li>
    Whether the thing in question <strong>causes</strong> or <strong>prevents</strong> cancer.
  </li>
</ul>
<p>
  I’ll then collate your research into a summary so that we
  all know how best to live our lives.
</p>
<% if @percent_complete < 100 %>
  <p>
    <%= link_to "Get started!", new_vote_path %>
  </p>
<% else %>
  <p>
    We’ve done it! <%= link_to "See the results.", "/" %> You can still <%= link_to "try voting", new_vote_path %> if you’re interested in seeing how it worked.
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Kill or cure?</title>
    <%= stylesheet_link_tag "reset-min", "basic", "screen" %>
  </head>
  <body>
    <div id="header">
      <h1><%= link_to "Kill or cure?", "/" %></h1>
      <p>
        Help to make sense of the Daily Mail’s ongoing effort to classify every
        inanimate object into those that cause cancer and those that prevent
        it.
      </p>
      <p id="percentComplete"><%= @percent_complete %>% done</p>
    </div>
    <div id="main">
      <%= yield %>
    </div>
    <div id="footer">
      <p>
        Made by <a href="http://po-ru.com/">Paul Battley</a> (<a href="http://twitter.com/threedaymonk">@threedaymonk</a>).
        <%= link_to "Source code", "https://github.com/threedaymonk/kill-or-cure" %>.
        <%= link_to "What’s all this about?", homepage_path %>
      </p>
    </div>
    <script type="text/javascript" src="http://www.google-analytics.com/ga.js"></script>
    <script type="text/javascript">
      try { var pageTracker = _gat._getTracker("UA-577248-3"); pageTracker._trackPageview(); } catch(err) {}
    </script>
  </body>
</html>

app/views/results/_pagination.html.erb
<ul class="pagination">
  <% @letters.each do |letter| %>
    <% if @letter == letter %>
      <li><strong><%= letter.upcase %></strong></li>
    <% else %>
      <li><%= link_to letter.upcase, results_path(:letter => letter) %></li>
    <% end %>
  <% end %>
</ul>

app/views/results/index.html.erb
<%= render :partial => "pagination" %>

<p>
  If any of these results seems incorrect, please report it using the link next to the article.
</p>

<% @terms.each do |term| %>
  <% next unless term.articles.any? %>

  <h2 id="term<%= term.id %>" class="termHeading <%= term.effect %>">
    <em><%= h(term.value) %></em>
    <% case term.effect; when :cause %>
      <strong class="cause">cause<%= "s" unless term.plural? %></strong>
    <% when :prevent %>
      <strong class="prevent">prevent<%= "s" unless term.plural? %></strong>
    <% when :both %>
      both <strong class="cause">cause<%= "s" unless term.plural? %></strong>
      and <strong class="prevent">prevent<%= "s" unless term.plural? %></strong>
    <% end %>
    cancer
    <a href="#term<%= term.id %>" class="directLink">#</a>
  </h2>

  <% if term.causes? %>
    <ul class="cause">
      <% term.causes_articles.each do |article| %>
        <li>
          <%= link_to article.title, article.link %>
        </li>
      <% end %>
    </ul>
  <% end %>

  <% if term.prevents? %>
    <ul class="prevent">
      <% term.prevents_articles.each do |article| %>
        <li>
          <%= link_to article.title, article.link %>
        </li>
      <% end %>
    </ul>
  <% end %>
<% end %>

<%= render :partial => "pagination" %>

app/views/stats/index.html.erb
<table>
  <tr>
    <th>Title</th>
    <th>Votes</th>
    <th>Cause</th>
    <th>Prevent</th>
  </tr>
  <% @articles.each do |article| %>
    <tr>
      <td><%= h(truncate(article.title, :length => 50)) %></td>
      <td><%= article.votes.length %></td>
      <td><%= h(article.causes * ", ") %></td>
      <td><%= h(article.preventors * ", ") %></td>
    </tr>
  <% end %>
</table>
<div>
  <%= will_paginate @articles %>
</div>

app/views/votes/done.html.erb
<h2>All done</h2>

<p>Thanks for all your efforts! We've now classifed all the articles. You can <%= link_to "browse the interim results", "/stats" %>, and I'll make the full dataset available shortly.</p>

app/views/votes/new.html.erb
<div id="summary">
  <h2><%= link_to h(@article.title), @article.link, :target => "_blank" %></h2>
  <p><%= h @article.summary %></p>
</div>

<div id="classify">
  <% form_for @vote do |f| %>
    <%= f.hidden_field :article_id %>

    <div class="row">
      <%= f.label :general, "What kind of a thing is it?" %>
      <%= f.text_field :general %>
    </div>

    <ul>
      <li>
        Be <strong>as terse as possible</strong>, e.g. “wine”, “sun”, “HRT”.
      </li>
      <li>
        If the article refers to more than one thing, <strong>separate them with commas</strong>, e.g.
        “fruit, vegetables”.
      </li>
      <li>
        <strong>Capital letters don’t matter</strong>.
      </li>
      <li>
        If the article isn’t about something that causes or prevents cancer, or if it’s ambiguous, choose <strong>neither</strong>.
      </li>
    </ul>

    <div class="row">
      <%= f.submit "Causes cancer",   :name => "cause" %>
      <%= f.submit "Prevents cancer", :name => "prevent" %>
      <%= f.submit "Neither",         :name => "skip" %>
    </div>

  <% end %>
</div>